cse-config-order: 100

## Spring Boot configurations
server:
  port: 9093

## CSE configurations
APPLICATION_ID: houseapp
service_description:
  name: customer-service
  version: 0.0.1
  environment: development
cse:
  service:
    registry:
      address: https://cse.cn-north-1.myhuaweicloud.com
      instance:
        watch: false
  config:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com
      refreshMode: 1
      refresh_interval: 5000
  monitor:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com
  rest:
    address: 0.0.0.0:9093
    server:
      thread-count: 10
  credentials:
    accessKey: BUDCVWSAW04UZVLSZBQR
    secretKey: BHixEctCJFbTkPUVUUjRDSeVwMAknlAy5oB7idgR
    akskCustomCipher: default

  handler:
    chain:
      Provider:
        default: perf-stats,qps-flowcontrol-provider,bizkeeper-provider,tcc-provider,twoPC-provider
      Consumer:
        default: perf-stats,qps-flowcontrol-consumer,loadbalance,bizkeeper-consumer,tcc-consumer,twoPC-consumer